name: hyp3-isce3-subset
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.12,<3.13
  - pip
  # For packaging, and testing
  - setuptools_scm
  - pytest
  - pytest-console-scripts
  - pytest-cov
  - pytest-mock
  # For running
  - asf_search
  - earthaccess
  - gdal
  - isce3
  - hyp3lib>=3,<4
  - libgdal-hdf5
  - pandas<3
  - pyaps3
  - pygrib
  - pyproj
  - raider>=0.4.5,<0.5.4
  - snaphu
  - utm
  # TODO: insert conda-forge dependencies as list here
  - pip:
      - -r requirements-static.txt
