name: Test

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  tests:
    uses: ASFHyP3/actions/.github/workflows/reusable-pixi-tasks.yml@v0.22.0
    with:
      environments: >-
        ["py312", "py313", "py314"]
      tasks: >-
        ["tests"]
    permissions:
      contents: read
